# Generated by Django 3.1.7 on 2021-03-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BWSvg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforeimage',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
